language: node_js
node_js:
  - "10"

before_script:
  - npm install gulp-cli
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.59.1_Linux-64bit.deb

script:
 - gulp
 - hugo --ignoreCache
 - cp CNAME public/ 2>/dev/null

cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - emmanuel.thomas@tno.nl
      - wilaw@akamai.com
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: hugo
    repo: Dash-Industry-Forum/Dash-Industry-Forum.github.io
  target-branch: master
  local-dir: public
