language: node_js
node_js:
  - "node"

before_script:
  - npm install gulp-cli
  - travis_wait sudo apt-get update -qq
  - travis_wait sudo apt-get install -y snapd
  - sudo snap install hugo --classic

script:
 - gulp
 - /snap/bin/hugo

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
  local-dir: public
