language: node_js
node_js:
  - "node"

before_script:
  - npm install gulp-cli
  - travis_wait sudo apt-get update -qq
  - travis_wait sudo apt-get install -y snapd
  - sudo snap install hugo --classic

script:
 - gulp
 - /snap/bin/hugo
 - cp CNAME public/

cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - emmanuel.thomas@tno.nl
      - wilaw@akamai.com
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: hugo
  target-branch: master
  local-dir: public
