language: node_js
node_js:
  - "node"

before_script:
  - npm install -g gulp-cli
  - sudo apt-get update
  - sudo apt-get install -y hugo

script:
 - gulp
 - hugo

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
  local-dir: public
