baseURL = "https://dash-industry-forum.github.io/"
languageCode = "en-us"
title = "DASH Industry Forum"

[menu]

  [[menu.main]]
    identifier = "guidelines"
    name = "guidelines"
    url = "guidelines/earlier-versions"
    title = "Guidelines"
    weight = 3

  [[menu.main]]
    identifier = "tools"
    name = "tools"
    url = "tools/introduction"
    title = "Reference Tools"
    weight = 4
  
  [[menu.main]]
    identifier = "identifiers"
    name = "identifiers"
    url = "identifiers/Introduction"
    title = "Identifiers"
    weight = 5
  
  [[menu.main]]
    identifier = "codecs"
    name = "codecs"
    url = "codecs/Introduction"
    title = "Codecs"
    weight = 6

  [[menu.main]]
    identifier = "events"
    name = "events"
    url = "events/events"
    title = "Events"
    weight = 10
