baseURL = "https://dash-industry-forum.github.io/"
languageCode = "en-us"
title = "DASH Industry Forum"

[menu]

  [[menu.main]]
    identifier = "guidelines"
    name = "guidelines"
    title= "Guidelines"
    weight= 3

  [[menu.main]]
    identifier = "test assets"
    name = "test assets"
    url = "https://testassets.dashif.org/"
    title= "Test Assets"
    weight= 4
  
  [[menu.main]]
    identifier = "identifiers"
    name = "identifiers"
    title= "Identifiers"
    weight= 5
  
  [[menu.main]]
    identifier = "codecs"
    name = "codecs"
    title= "Codecs
    weight= 6
