name: Publication to Github Pages

on:
  push:
    #TODO: to change to hugo
    branches: [ edrthomas-to-github-ci ] 

jobs:
  publish:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name:  Update repo
      run: sudo apt-get update
    - name:  Configure nodejs, npm
      run: |
        sudo apt-get install npm nodejs
        echo "node version:"
        node --version
        echo "npm version:"
        npm --version
    - name: Install hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
        sudo dpkg -i hugo_0.59.1_Linux-64bit.deb
    - name: Install js dependencies
      run: |
        npm install
        echo "gulp version:"
        gulp --version
    - name: Build website assets
      run: gulp
    - name: Compile website
      run: hugo --ignoreCache
    - name: Copy CNAME
      run: CNAME public/ 2>/dev/null
